name: signature_volt_link
description: Create your Volt mail signature.

publish_to: 'none'


version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  url_launcher: ^6.0.20
  equatable: ^2.0.3
  formz: ^0.4.1
  html_editor_enhanced: ^2.4.0
  flutter_modular: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  mocktail: ^0.2.0
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/volt_logo_purple.svg
    - assets/html/signature.txt

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700